"
OTHER BUILT-IN TYPES

There are a few other types in Elixir:

  - A 'reference': an almost unique piece of info in a BEAM instance.
                   A reference is generated by calling Kernel.make_ref/0
                   (or make_ref). A reference will reoccur after approx.
                   2^82 calls. But reference generation starts from the
                   beginning when you restart a BEAM instance. So its
                   uniqueness is only guaranteed during the lifetime of
                   the BEAM instance.
  - A 'pid': (process id) identifies an Erlang process. Pids are useful
                   when cooperating between concurrent tasks.
  - The 'port identifier' is important when using ports. It is a mechanism
                   used in Erlang to talk to the outside world. File I/O
                   and communication with external programs are done through
                   ports.
"
|> IO.puts()
